name: Eighth Workflow
on:
  workflow_dispatch

jobs:
  run-first:
    runs-on: ubuntu-latest
    steps:
      - name: Display event variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF