name: Fifteenth Workflow
on: push

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Math Expression
        run: expr 2 + 2 > math-result.txt
      - name: Upload the rusult file
        uses: actions/upload-artifact@v4
        with:
          name: math-result
          path: math-result.txt
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: math-result
      - name: Print File
        run: |
          value=`cat math-result.txt`
          echo $value
