name: Fourth Workflow
on:
  workflow_run:
    workflows: ["Third Workflow"]
    types:
      - completed

jobs:
  success-command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: Successful
        run: |
          echo "Success"
          echo "Event conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Event name: ${{ github.event.workflow_run.name }}"
  failure-command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - name: Failure
        run: echo "Failure"
