name: Sixteenth Worflow
on: push

jobs:
  testing-matrix-job:
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-versions: [12, 14, 18]
        include:
          - os: macos-latest
            node-versions: 17
        exclude:
          - os: ubuntu-latest
            node-versions: 14
    runs-on: ${{matrix.os}}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions}}
      - run: node -v