name: Sixteenth Worflow
on: push

jobs:
  testing-matrix-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-versions: [12, 14, 18]
    runs-on: ${{matrix.os}}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions}}
      - run: node -v