name: Third Workflow
on: push
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
      - name: Copy Files
        run: |
          git init
          git remote  add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files
        run: ls -la
      - name: Debug - Print workflow info
        run: |
          echo "Workflow name: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"