name: Thirteenth Workflow
on: push

jobs:
  first-job:
#    failure() success() always() canceled()
    runs-on: ubuntu-latest
    steps:
      - name: Erroneous Step
        id: erroneous-step
#        run: sleep 30
        run: exit 1

      - name: Runs on Canceled
        if: ${{cancelled()}}
        run: echo "Runs on Canceled! ğŸš«"

      - name: Runs in any case
        if: ${{always()}}
        run: echo "Runs in any case! ğŸš€"

      - name: Runs on Success
        if: ${{success()}}
        run: echo "Runs on success! ğŸ‰"

      - name: Runs on Failure
        if: ${{failure() && steps.erroneous-step.conclusion == 'failure'}}
        run: echo "Runs on failure! ğŸ’©"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    if: ${{failure()}}
    steps:
      - run: echo "First job is failed â˜¹ï¸"
