name: Twelfth Workflow
on: push

jobs:
  run-first:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Our vars and secrets
        run: |
          echo '${{vars.STATUS}}'
          echo '${{secrets.PASSWORD}}'